version: "3"

networks:
  monitoring:
    internal: true
services:
 node-exporter:
    build: ./node
    container_name: nodeexporter
    ports:
      - "9101:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - monitoring
      - default
    restart: always

 cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /cgroup:/cgroup:ro
      - /var/run:/var/run:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /cgroup:/sys/fs/cgroup:ro
    networks:
      - monitoring
      - default
    restart: always